name: "X=sss120,A=sss120,d=s0\""
operators {
  name: "fiberlookup"
  id: 18
  fiber_lookup {
    output_ref {
      id {
        id: 18
      }
    }
    output_crd {
      id {
        id: 17
      }
      name: "in-d"
    }
    index: "j"
    tensor: "d"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup j: d0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 17
  fiber_lookup {
    output_ref {
      id {
        id: 16
      }
    }
    output_crd {
      id {
        id: 1
      }
      name: "in-A"
    }
    index: "j"
    tensor: "A"
    mode: 1
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup j: A1\\ncompressed"
  }
}
operators {
  name: "union"
  id: 16
  joiner {
    join_type: UNION
    input_pairs {
      crd {
        id {
          id: 1
        }
        name: "crd_in-A"
      }
      ref {
        id {
          id: 16
        }
        name: "ref_in-A"
      }
    }
    input_pairs {
      crd {
        id {
          id: 17
        }
        name: "crd_in-d"
      }
      ref {
        id {
          id: 18
        }
        name: "ref_in-d"
      }
    }
    index: "j"
    label: "union j"
    output_ref1 {
      id {
        id: 3
      }
      name: "out-A"
    }
    output_ref2 {
      id {
        id: 15
      }
      name: "out-d"
    }
    output_crd {
      id {
        id: 2
      }
    }
  }
}
operators {
  name: "fiberlookup"
  id: 15
  fiber_lookup {
    input_ref {
      id {
        id: 3
      }
      name: "ref_out-A"
    }
    output_ref {
      id {
        id: 10
      }
    }
    output_crd {
      id {
        id: 4
      }
    }
    index: "k"
    tensor: "A"
    mode: 2
    format: "compressed"
    src: true
    label: "FiberLookup k: A2\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 13
  repeatsig {
    input_crd {
      id {
        id: 4
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 5
      }
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 12
  repeat {
    input_ref {
      id {
        id: 15
      }
      name: "ref_out-d"
    }
    output_ref {
      id {
        id: 6
      }
    }
    input_rep_sig {
      id {
        id: 5
      }
      name: "repsig"
    }
    label: "Repeat k: d"
    index: "k"
    tensor: "d"
  }
}
operators {
  name: "fiberlookup"
  id: 11
  fiber_lookup {
    input_ref {
      id {
        id: 10
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 13
      }
    }
    output_crd {
      id {
        id: 11
      }
    }
    index: "i"
    tensor: "A"
    format: "compressed"
    src: true
    label: "FiberLookup i: A0\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 9
  repeatsig {
    input_crd {
      id {
        id: 11
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 12
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 8
  repeat {
    input_ref {
      id {
        id: 6
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 7
      }
    }
    input_rep_sig {
      id {
        id: 12
      }
      name: "repsig"
    }
    label: "Repeat i: d"
    index: "i"
    tensor: "d"
  }
}
operators {
  name: "arrayvals"
  id: 7
  array {
    tensor: "d"
    input_ref {
      id {
        id: 7
      }
      name: "ref"
    }
    output_val {
      id {
        id: 8
      }
      name: "val"
    }
    label: "Array Vals: d"
  }
}
operators {
  name: "arrayvals"
  id: 6
  array {
    tensor: "A"
    input_ref {
      id {
        id: 13
      }
      name: "ref"
    }
    output_val {
      id {
        id: 14
      }
      name: "val"
    }
    label: "Array Vals: A"
  }
}
operators {
  name: "add"
  id: 5
  alu {
    vals {
      inputs {
        id {
          id: 8
        }
        name: "val"
      }
      inputs {
        id {
          id: 14
        }
        name: "val"
      }
      output {
        id {
          id: 9
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
    }
    label: "Add"
  }
}
operators {
  name: "fiberwrite"
  id: 4
  fiber_write {
    input_crd {
      id {
        id: 2
      }
      name: "crd"
    }
    index: "j"
    tensor: "X"
    format: "compressed"
    segsize: "2"
    crdsize: "A1_dim"
    sink: true
    label: "FiberWrite j: X1\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 4
      }
      name: "crd"
    }
    index: "k"
    tensor: "X"
    format: "compressed"
    segsize: "A1_dim+1"
    crdsize: "A1_dim*A2_dim"
    sink: true
    label: "FiberWrite k: X2\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 11
      }
      name: "crd"
    }
    index: "i"
    tensor: "X"
    format: "compressed"
    segsize: "A1_dim*A2_dim+1"
    crdsize: "A1_dim*A2_dim*A0_dim"
    sink: true
    label: "FiberWrite i: X0\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 9
      }
      name: "val"
    }
    label: "FiberWrite Vals: X"
    crdsize: "1*A1_dim*A2_dim*A0_dim"
    tensor: "X"
    sink: true
  }
}

