name: "comal graph"
channel_size: 1024
graph {
  operators {
    name: "root"
    id: 1
    root {
      label: "root t0"
      output_ref {
        id {
          id: 1
        }
      }
    }
  }
  operators {
    name: "fiberlookup"
    id: 2
    fiber_lookup {
      input_ref {
        id {
          id: 1
        }
      }
      output_ref {
        id {
          id: 2
        }
      }
      output_crd {
        id {
          id: 3
        }
      }
      index: "d0"
      tensor: "t0"
      format: "dense"
      label: "fiberlookup d0"
    }
  }
  operators {
    name: "root"
    id: 3
    root {
      label: "root t1"
      output_ref {
        id {
          id: 4
        }
      }
    }
  }
  operators {
    name: "repeat"
    id: 4
    repeat {
      input_ref {
        id {
          id: 4
        }
      }
      output_ref {
        id {
          id: 5
        }
      }
      label: "repeat d0: t1"
      index: "d0"
      tensor: "t1"
      input_rep_crd {
        id {
          id: 2
        }
      }
    }
  }
  operators {
    name: "fiberlookup"
    id: 5
    fiber_lookup {
      input_ref {
        id {
          id: 5
        }
      }
      output_ref {
        id {
          id: 6
        }
      }
      output_crd {
        id {
          id: 7
        }
      }
      index: "d1"
      tensor: "t1"
      mode: 1
      format: "dense"
      label: "fiberlookup d1"
    }
  }
  operators {
    name: "repeat"
    id: 6
    repeat {
      input_ref {
        id {
          id: 2
        }
      }
      output_ref {
        id {
          id: 8
        }
      }
      label: "repeat d1: t0"
      index: "d1"
      tensor: "t0"
      input_rep_crd {
        id {
          id: 6
        }
      }
    }
  }
  operators {
    name: "fiberlookup"
    id: 7
    fiber_lookup {
      input_ref {
        id {
          id: 8
        }
      }
      output_ref {
        id {
          id: 9
        }
      }
      output_crd {
        id {
          id: 10
        }
      }
      index: "d2"
      tensor: "t0"
      mode: 1
      format: "compressed"
      label: "fiberlookup d2"
    }
  }
  operators {
    name: "fiberlookup"
    id: 8
    fiber_lookup {
      input_ref {
        id {
          id: 6
        }
      }
      output_ref {
        id {
          id: 11
        }
      }
      output_crd {
        id {
          id: 12
        }
      }
      index: "d2"
      tensor: "t1"
      format: "dense"
      label: "fiberlookup d2"
    }
  }
  operators {
    name: "intersect"
    id: 9
    joiner {
      input_pairs {
        crd {
          id {
            id: 10
          }
        }
        ref {
          id {
            id: 9
          }
        }
      }
      input_pairs {
        crd {
          id {
            id: 12
          }
        }
        ref {
          id {
            id: 11
          }
        }
      }
      index: "d2"
      label: "intersect d2"
      output_refs {
        id {
          id: 13
        }
      }
      output_refs {
        id {
          id: 14
        }
      }
      output_crd {
        id {
        }
      }
    }
  }
  operators {
    name: "arrayval"
    id: 10
    array {
      tensor: "t0"
      input_ref {
        id {
          id: 13
        }
      }
      output_val {
        id {
          id: 16
        }
      }
      label: "arrayval t0"
    }
  }
  operators {
    name: "arrayval"
    id: 11
    array {
      tensor: "t1"
      input_ref {
        id {
          id: 14
        }
      }
      output_val {
        id {
          id: 17
        }
      }
      label: "arrayval t1"
    }
  }
  operators {
    name: "mul"
    id: 12
    alu {
      vals {
        inputs {
          id {
            id: 16
          }
        }
        inputs {
          id {
            id: 17
          }
        }
        output {
          id {
            id: 18
          }
        }
      }
      stages {
        inputs: 0
        inputs: 1
        op: MUL
      }
      label: "mul"
    }
  }
  operators {
    name: "reduce"
    id: 13
    reduce {
      input_val {
        id {
          id: 18
        }
      }
      output_val {
        id {
        }
      }
      label: "reduce"
    }
  }
  operators {
    name: "fiberwrite"
    id: 14
    fiber_write {
      input_crd {
        id {
          id: 3
        }
      }
      index: "d0"
      tensor: "t0"
      format: "dense"
      label: "fiberwrite d0"
    }
  }
  operators {
    name: "fiberwrite"
    id: 15
    fiber_write {
      input_crd {
        id {
          id: 7
        }
      }
      index: "d1"
      tensor: "t1"
      format: "dense"
      label: "fiberwrite d1"
    }
  }
  operators {
    name: "valwrite"
    id: 16
    val_write {
      input_val {
        id {
          id: 19
        }
      }
      label: "valwrite"
    }
  }
}
