name: "comal graph"
channel_size: 1024
graph {
  name: "X=ss01,E=ss01,F=ss10,C=ss10,d=s0"
  operators {
    name: "fiberlookup"
    id: 2
    fiber_lookup {
      output_ref {
        id {
          id: 1
        }
      }
      output_crd {
        id {
          id: 2
        }
      }
      index: "j"
      tensor: "E"
      format: "compressed"
      src: true
      root: true
      label: "FiberLookup j: E0\\ncompressed"
    }
  }
  operators {
    name: "repsiggen"
    id: 3
    repeatsig {
      input_crd {
        id {
          id: 44
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 3
        }
      }
      label: "RepeatSignalGenerator j"
      index: "j"
    }
  }
  operators {
    name: "repeat"
    id: 4
    repeat {
      output_ref {
        id {
          id: 4
        }
      }
      input_rep_sig {
        id {
          id: 3
        }
        name: "repsig"
      }
      label: "Repeat j: F"
      index: "j"
      root: true
      tensor: "F"
    }
  }
  operators {
    name: "fiberlookup"
    id: 5
    fiber_lookup {
      input_ref {
        id {
          id: 4
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 5
        }
      }
      output_crd {
        id {
          id: 6
        }
      }
      index: "l"
      tensor: "F"
      mode: 1
      format: "compressed"
      src: true
      label: "FiberLookup l: F1\\ncompressed"
    }
  }
  operators {
    name: "repsiggen"
    id: 6
    repeatsig {
      input_crd {
        id {
          id: 47
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 7
        }
      }
      label: "RepeatSignalGenerator l"
      index: "l"
    }
  }
  operators {
    name: "repeat"
    id: 7
    repeat {
      input_ref {
        id {
          id: 1
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 8
        }
      }
      input_rep_sig {
        id {
          id: 7
        }
        name: "repsig"
      }
      label: "Repeat l: E"
      index: "l"
      tensor: "E"
    }
  }
  operators {
    name: "fiberlookup"
    id: 8
    fiber_lookup {
      input_ref {
        id {
          id: 49
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 9
        }
      }
      output_crd {
        id {
          id: 10
        }
        name: "in-F"
      }
      index: "i"
      tensor: "F"
      format: "compressed"
      src: true
      label: "FiberLookup i: F0\\ncompressed"
    }
  }
  operators {
    name: "fiberlookup"
    id: 9
    fiber_lookup {
      input_ref {
        id {
          id: 8
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 11
        }
      }
      output_crd {
        id {
          id: 12
        }
        name: "in-E"
      }
      index: "i"
      tensor: "E"
      mode: 1
      format: "compressed"
      src: true
      label: "FiberLookup i: E1\\ncompressed"
    }
  }
  operators {
    name: "intersect"
    id: 10
    joiner {
      input_pairs {
        crd {
          id {
            id: 12
          }
          name: "crd_in-E"
        }
        ref {
          id {
            id: 11
          }
          name: "ref_in-E"
        }
      }
      input_pairs {
        crd {
          id {
            id: 10
          }
          name: "crd_in-F"
        }
        ref {
          id {
            id: 9
          }
          name: "ref_in-F"
        }
      }
      index: "i"
      label: "intersect i"
      output_ref1 {
        id {
          id: 13
        }
        name: "out-E"
      }
      output_ref2 {
        id {
          id: 14
        }
        name: "out-F"
      }
      output_crd {
        id {
        }
        name: "in-i"
      }
    }
  }
  operators {
    name: "arrayvals"
    id: 13
    array {
      tensor: "F"
      input_ref {
        id {
          id: 14
        }
        name: "ref_out-F"
      }
      output_val {
        id {
          id: 16
        }
        name: "val"
      }
      label: "Array Vals: F"
    }
  }
  operators {
    name: "arrayvals"
    id: 14
    array {
      tensor: "E"
      input_ref {
        id {
          id: 13
        }
        name: "ref_out-E"
      }
      output_val {
        id {
          id: 17
        }
        name: "val"
      }
      label: "Array Vals: E"
    }
  }
  operators {
    name: "mul"
    id: 15
    alu {
      vals {
        inputs {
          id {
            id: 17
          }
          name: "val"
        }
        inputs {
          id {
            id: 16
          }
          name: "val"
        }
        output {
          id {
            id: 18
          }
          name: "val"
        }
      }
      stages {
        inputs: 0
        inputs: 1
        op: MUL
      }
      label: "Mul"
    }
  }
  operators {
    name: "reduce"
    id: 16
    reduce {
      input_val {
        id {
          id: 18
        }
        name: "val"
      }
      output_val {
        id {
          id: 19
        }
        name: "reduce_val"
      }
    }
  }
  operators {
    name: "repsiggen"
    id: 21
    repeatsig {
      input_crd {
        id {
          id: 45
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 20
        }
      }
      label: "RepeatSignalGenerator j"
      index: "j"
    }
  }
  operators {
    name: "repeat"
    id: 22
    repeat {
      output_ref {
        id {
          id: 21
        }
      }
      input_rep_sig {
        id {
          id: 20
        }
        name: "repsig"
      }
      label: "Repeat j: C"
      index: "j"
      root: true
      tensor: "C"
    }
  }
  operators {
    name: "fiberlookup"
    id: 23
    fiber_lookup {
      input_ref {
        id {
          id: 21
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 22
        }
      }
      output_crd {
        id {
          id: 23
        }
      }
      index: "k"
      tensor: "C"
      mode: 1
      format: "compressed"
      src: true
      label: "FiberLookup k: C1\\ncompressed"
    }
  }
  operators {
    name: "repsiggen"
    id: 24
    repeatsig {
      input_crd {
        id {
          id: 51
        }
        name: "crd"
      }
      output_rep_sig {
        id {
        }
      }
      label: "RepeatSignalGenerator k"
      index: "k"
    }
  }
  operators {
    name: "fiberlookup"
    id: 26
    fiber_lookup {
      input_ref {
        id {
          id: 22
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 25
        }
      }
      output_crd {
        id {
          id: 26
        }
        name: "in-C"
      }
      index: "l"
      tensor: "C"
      format: "compressed"
      src: true
      label: "FiberLookup l: C0\\ncompressed"
    }
  }
  operators {
    name: "intersect"
    id: 28
    joiner {
      input_pairs {
        crd {
          id {
            id: 48
          }
          name: "crd_in-B"
        }
        ref {
          id {
            id: 50
          }
          name: "ref_in-B"
        }
      }
      input_pairs {
        crd {
          id {
            id: 26
          }
          name: "crd_in-C"
        }
        ref {
          id {
            id: 25
          }
          name: "ref_in-C"
        }
      }
      index: "l"
      label: "intersect l"
      output_ref1 {
        id {
        }
        name: "out-B"
      }
      output_ref2 {
        id {
          id: 28
        }
        name: "out-C"
      }
      output_crd {
        id {
        }
        name: "in-l"
      }
    }
  }
  operators {
    name: "arrayvals"
    id: 29
    array {
      tensor: "C"
      input_ref {
        id {
          id: 28
        }
        name: "ref_out-C"
      }
      output_val {
        id {
          id: 30
        }
        name: "val"
      }
      label: "Array Vals: C"
    }
  }
  operators {
    name: "mul"
    id: 31
    alu {
      vals {
        inputs {
          id {
            id: 19
          }
          name: "val"
        }
        inputs {
          id {
            id: 30
          }
          name: "val"
        }
        output {
          id {
            id: 31
          }
          name: "val"
        }
      }
      stages {
        inputs: 0
        inputs: 1
        op: MUL
      }
      label: "Mul"
    }
  }
  operators {
    name: "reduce"
    id: 32
    reduce {
      input_val {
        id {
          id: 31
        }
        name: "val"
      }
      output_val {
        id {
          id: 32
        }
        name: "reduce_val"
      }
    }
  }
  operators {
    name: "fiberlookup"
    id: 33
    fiber_lookup {
      output_ref {
        id {
          id: 33
        }
      }
      output_crd {
        id {
          id: 34
        }
        name: "in-d"
      }
      index: "j"
      tensor: "d"
      format: "compressed"
      src: true
      root: true
      label: "FiberLookup j: d0\\ncompressed"
    }
  }
  operators {
    name: "union"
    id: 34
    joiner {
      join_type: UNION
      input_pairs {
        crd {
          id {
            id: 46
          }
          name: "crd_in-A"
        }
        ref {
          id {
            id: 35
          }
          name: "ref_in-A"
        }
      }
      input_pairs {
        crd {
          id {
            id: 34
          }
          name: "crd_in-d"
        }
        ref {
          id {
            id: 33
          }
          name: "ref_in-d"
        }
      }
      index: "j"
      label: "union j"
      output_ref1 {
        id {
        }
        name: "out-A"
      }
      output_ref2 {
        id {
          id: 37
        }
        name: "out-d"
      }
      output_crd {
        id {
          id: 38
        }
      }
    }
  }
  operators {
    name: "repsiggen"
    id: 35
    repeatsig {
      input_crd {
        id {
          id: 52
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 39
        }
      }
      label: "RepeatSignalGenerator k"
      index: "k"
    }
  }
  operators {
    name: "repeat"
    id: 36
    repeat {
      input_ref {
        id {
          id: 37
        }
        name: "ref_out-d"
      }
      output_ref {
        id {
          id: 40
        }
      }
      input_rep_sig {
        id {
          id: 39
        }
        name: "repsig"
      }
      label: "Repeat k: d"
      index: "k"
      tensor: "d"
    }
  }
  operators {
    name: "arrayvals"
    id: 37
    array {
      tensor: "d"
      input_ref {
        id {
          id: 40
        }
        name: "ref"
      }
      output_val {
        id {
          id: 41
        }
        name: "val"
      }
      label: "Array Vals: d"
    }
  }
  operators {
    name: "add"
    id: 38
    alu {
      vals {
        inputs {
          id {
            id: 41
          }
          name: "val"
        }
        inputs {
          id {
            id: 32
          }
          name: "val"
        }
        output {
          id {
            id: 42
          }
          name: "val"
        }
      }
      stages {
        inputs: 0
        inputs: 1
      }
      label: "Add"
    }
  }
  operators {
    name: "fiberwrite"
    id: 39
    fiber_write {
      input_crd {
        id {
          id: 38
        }
        name: "crd"
      }
      index: "j"
      tensor: "X"
      format: "compressed"
      segsize: "2"
      crdsize: "A0_dim"
      sink: true
      label: "FiberWrite j: X0\\ncompressed"
    }
  }
  operators {
    name: "fiberwrite"
    id: 40
    fiber_write {
      input_crd {
        id {
          id: 53
        }
        name: "crd"
      }
      index: "k"
      tensor: "X"
      format: "compressed"
      segsize: "A0_dim+1"
      crdsize: "A0_dim*A1_dim"
      sink: true
      label: "FiberWrite k: X1\\ncompressed"
    }
  }
  operators {
    name: "valwrite"
    id: 41
    val_write {
      input_val {
        id {
          id: 42
        }
        name: "val"
      }
      label: "FiberWrite Vals: X"
      crdsize: "1*A0_dim*A1_dim"
      tensor: "X"
      sink: true
    }
  }
  operators {
    name: "broadcast"
    id: 42
    broadcast {
      crd {
        input {
          id {
            id: 2
          }
          name: "crd"
        }
        outputs {
          id {
            id: 44
          }
        }
        outputs {
          id {
            id: 45
          }
        }
        outputs {
          id {
            id: 46
          }
        }
      }
    }
  }
  operators {
    name: "broadcast"
    id: 43
    broadcast {
      crd {
        input {
          id {
            id: 6
          }
          name: "crd"
        }
        outputs {
          id {
            id: 47
          }
        }
        outputs {
          id {
            id: 48
          }
        }
      }
    }
  }
  operators {
    name: "broadcast"
    id: 44
    broadcast {
      ref {
        input {
          id {
            id: 5
          }
          name: "ref"
        }
        outputs {
          id {
            id: 49
          }
        }
        outputs {
          id {
            id: 50
          }
        }
      }
    }
  }
  operators {
    name: "broadcast"
    id: 45
    broadcast {
      crd {
        input {
          id {
            id: 23
          }
          name: "crd"
        }
        outputs {
          id {
            id: 51
          }
        }
        outputs {
          id {
            id: 52
          }
        }
        outputs {
          id {
            id: 53
          }
        }
      }
    }
  }
}
