name: "X=ss01,G=ss01,A=ss01,I=ss01,h=s0\""
operators {
  name: "fiberlookup"
  id: 41
  fiber_lookup {
    output_ref {
      id {
        id: 49
      }
    }
    output_crd {
      id {
        id: 48
      }
      name: "in-h"
    }
    index: "m"
    tensor: "h"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup m: h0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 40
  fiber_lookup {
    output_ref {
      id {
        id: 47
      }
    }
    output_crd {
      id {
        id: 1
      }
      name: "in-G"
    }
    index: "m"
    tensor: "G"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup m: G0\\ncompressed"
  }
}
operators {
  name: "union"
  id: 39
  joiner {
    join_type: UNION
    input_pairs {
      crd {
        id {
          id: 1
        }
        name: "crd_in-G"
      }
      ref {
        id {
          id: 47
        }
        name: "ref_in-G"
      }
    }
    input_pairs {
      crd {
        id {
          id: 48
        }
        name: "crd_in-h"
      }
      ref {
        id {
          id: 49
        }
        name: "ref_in-h"
      }
    }
    index: "m"
    label: "union m"
    output_ref1 {
      id {
        id: 43
      }
      name: "out-G"
    }
    output_ref2 {
      id {
        id: 46
      }
      name: "out-h"
    }
    output_crd {
      id {
        id: 2
      }
      name: "m"
    }
  }
}
operators {
  name: "repsiggen"
  id: 37
  repeatsig {
    input_crd {
      id {
        id: 2
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 7
      }
    }
    label: "RepeatSignalGenerator m"
    index: "m"
  }
}
operators {
  name: "repeat"
  id: 35
  repeat {
    output_ref {
      id {
        id: 42
      }
    }
    input_rep_sig {
      id {
        id: 7
      }
      name: "repsig"
    }
    label: "Repeat m: I"
    index: "m"
    root: true
    tensor: "I"
  }
}
operators {
  name: "repeat"
  id: 34
  repeat {
    output_ref {
      id {
        id: 8
      }
    }
    input_rep_sig {
      id {
        id: 7
      }
      name: "repsig"
    }
    label: "Repeat m: A"
    index: "m"
    root: true
    tensor: "A"
  }
}
operators {
  name: "fiberlookup"
  id: 33
  fiber_lookup {
    input_ref {
      id {
        id: 8
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 41
      }
    }
    output_crd {
      id {
        id: 9
      }
      name: "in-A"
    }
    index: "i"
    tensor: "A"
    format: "compressed"
    src: true
    label: "FiberLookup i: A0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 32
  fiber_lookup {
    input_ref {
      id {
        id: 43
      }
      name: "ref_out-G"
    }
    output_ref {
      id {
        id: 45
      }
    }
    output_crd {
      id {
        id: 44
      }
      name: "in-G"
    }
    index: "i"
    tensor: "G"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup i: G1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 31
  joiner {
    input_pairs {
      crd {
        id {
          id: 9
        }
        name: "crd_in-A"
      }
      ref {
        id {
          id: 41
        }
        name: "ref_in-A"
      }
    }
    input_pairs {
      crd {
        id {
          id: 44
        }
        name: "crd_in-G"
      }
      ref {
        id {
          id: 45
        }
        name: "ref_in-G"
      }
    }
    index: "i"
    label: "intersect i"
    output_ref1 {
      id {
        id: 38
      }
      name: "out-A"
    }
    output_ref2 {
      id {
        id: 37
      }
      name: "out-G"
    }
    output_crd {
      id {
        id: 10
      }
      name: "i"
    }
  }
}
operators {
  name: "repsiggen"
  id: 29
  repeatsig {
    input_crd {
      id {
        id: 10
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 15
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 28
  repeat {
    input_ref {
      id {
        id: 42
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 16
      }
    }
    input_rep_sig {
      id {
        id: 15
      }
      name: "repsig"
    }
    label: "Repeat i: I"
    index: "i"
    tensor: "I"
  }
}
operators {
  name: "fiberlookup"
  id: 27
  fiber_lookup {
    input_ref {
      id {
        id: 16
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 36
      }
    }
    output_crd {
      id {
        id: 17
      }
      name: "in-I"
    }
    index: "j"
    tensor: "I"
    format: "compressed"
    src: true
    label: "FiberLookup j: I0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 26
  fiber_lookup {
    input_ref {
      id {
        id: 38
      }
      name: "ref_out-A"
    }
    output_ref {
      id {
        id: 40
      }
    }
    output_crd {
      id {
        id: 39
      }
      name: "in-A"
    }
    index: "j"
    tensor: "A"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup j: A1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 25
  joiner {
    input_pairs {
      crd {
        id {
          id: 17
        }
        name: "crd_in-I"
      }
      ref {
        id {
          id: 36
        }
        name: "ref_in-I"
      }
    }
    input_pairs {
      crd {
        id {
          id: 39
        }
        name: "crd_in-A"
      }
      ref {
        id {
          id: 40
        }
        name: "ref_in-A"
      }
    }
    index: "j"
    label: "intersect j"
    output_ref1 {
      id {
        id: 28
      }
      name: "out-I"
    }
    output_ref2 {
      id {
        id: 25
      }
      name: "out-A"
    }
    output_crd {
      id {
        id: 18
      }
      name: "j"
    }
  }
}
operators {
  name: "repsiggen"
  id: 23
  repeatsig {
    input_crd {
      id {
        id: 18
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 19
      }
    }
    label: "RepeatSignalGenerator j"
    index: "j"
  }
}
operators {
  name: "repeat"
  id: 22
  repeat {
    input_ref {
      id {
        id: 37
      }
      name: "ref_out-G"
    }
    output_ref {
      id {
        id: 20
      }
    }
    input_rep_sig {
      id {
        id: 19
      }
      name: "repsig"
    }
    label: "Repeat j: G"
    index: "j"
    tensor: "G"
  }
}
operators {
  name: "fiberlookup"
  id: 21
  fiber_lookup {
    input_ref {
      id {
        id: 28
      }
      name: "ref_out-I"
    }
    output_ref {
      id {
        id: 34
      }
    }
    output_crd {
      id {
        id: 29
      }
    }
    index: "n"
    tensor: "I"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup n: I1\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 19
  repeatsig {
    input_crd {
      id {
        id: 29
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 30
      }
    }
    label: "RepeatSignalGenerator n"
    index: "n"
  }
}
operators {
  name: "repeat"
  id: 17
  repeat {
    input_ref {
      id {
        id: 46
      }
      name: "ref_out-h"
    }
    output_ref {
      id {
        id: 31
      }
    }
    input_rep_sig {
      id {
        id: 30
      }
      name: "repsig"
    }
    label: "Repeat n: h"
    index: "n"
    tensor: "h"
  }
}
operators {
  name: "repeat"
  id: 16
  repeat {
    input_ref {
      id {
        id: 25
      }
      name: "ref_out-A"
    }
    output_ref {
      id {
        id: 26
      }
    }
    input_rep_sig {
      id {
        id: 30
      }
      name: "repsig"
    }
    label: "Repeat n: A"
    index: "n"
    tensor: "A"
  }
}
operators {
  name: "repeat"
  id: 15
  repeat {
    input_ref {
      id {
        id: 20
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 21
      }
    }
    input_rep_sig {
      id {
        id: 30
      }
      name: "repsig"
    }
    label: "Repeat n: G"
    index: "n"
    tensor: "G"
  }
}
operators {
  name: "crddrop"
  id: 14
  coord_drop {
    input_inner_crd {
      id {
        id: 18
      }
      name: "crd_j"
    }
    input_outer_crd {
      id {
        id: 10
      }
      name: "crd_i"
    }
    output_inner_crd {
      id {
        id: 12
      }
      name: "inner-j"
    }
    output_outer_crd {
      id {
        id: 11
      }
      name: "outer-i"
    }
    inner_crd: "j"
    outer_crd: "i"
    label: "CrdDrop i,j"
  }
}
operators {
  name: "crddrop"
  id: 13
  coord_drop {
    input_inner_crd {
      id {
        id: 11
      }
      name: "crd_outer-i"
    }
    input_outer_crd {
      id {
        id: 2
      }
      name: "crd_m"
    }
    output_inner_crd {
      id {
        id: 4
      }
      name: "inner-i"
    }
    output_outer_crd {
      id {
        id: 3
      }
      name: "outer-m"
    }
    inner_crd: "i"
    outer_crd: "m"
    label: "CrdDrop m,i"
  }
}
operators {
  name: "arrayvals"
  id: 12
  array {
    tensor: "h"
    input_ref {
      id {
        id: 31
      }
      name: "ref"
    }
    output_val {
      id {
        id: 32
      }
      name: "val"
    }
    label: "Array Vals: h"
  }
}
operators {
  name: "arrayvals"
  id: 11
  array {
    tensor: "I"
    input_ref {
      id {
        id: 34
      }
      name: "ref"
    }
    output_val {
      id {
        id: 35
      }
      name: "val"
    }
    label: "Array Vals: I"
  }
}
operators {
  name: "arrayvals"
  id: 10
  array {
    tensor: "A"
    input_ref {
      id {
        id: 26
      }
      name: "ref"
    }
    output_val {
      id {
        id: 27
      }
      name: "val"
    }
    label: "Array Vals: A"
  }
}
operators {
  name: "arrayvals"
  id: 9
  array {
    tensor: "G"
    input_ref {
      id {
        id: 21
      }
      name: "ref"
    }
    output_val {
      id {
        id: 22
      }
      name: "val"
    }
    label: "Array Vals: G"
  }
}
operators {
  name: "mul"
  id: 8
  alu {
    vals {
      inputs {
        id {
          id: 22
        }
        name: "val"
      }
      inputs {
        id {
          id: 27
        }
        name: "val"
      }
      output {
        id {
          id: 23
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 7
  alu {
    vals {
      inputs {
        id {
          id: 23
        }
        name: "val"
      }
      inputs {
        id {
          id: 35
        }
        name: "val"
      }
      output {
        id {
          id: 24
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "spaccumulator"
  id: 6
  spacc {
    input_inner_crd {
      id {
        id: 29
      }
      name: "crd_n"
    }
    output_inner_crd {
      id {
        id: 14
      }
      name: "out-n"
    }
    input_outer_crds {
      id {
        id: 12
      }
      name: "crd_inner-j"
    }
    input_val {
      id {
        id: 24
      }
      name: "val"
    }
    output_val {
      id {
        id: 13
      }
    }
    order: 1
    inner_crd: "n"
    outer_crds: "j"
    outer_crds: "i"
    outer_crds: "n"
    outer_crds: "j"
    label: "SparseAccumulator 1 "
  }
}
operators {
  name: "spaccumulator"
  id: 5
  spacc {
    output_inner_crd {
      id {
        id: 6
      }
      name: "out-n"
    }
    input_outer_crds {
      id {
        id: 4
      }
      name: "crd_inner-i"
    }
    output_val {
      id {
        id: 5
      }
    }
    order: 2
    inner_crd: "n"
    outer_crds: "j"
    outer_crds: "i"
    label: "SparseAccumulator 2 "
  }
}
operators {
  name: "add"
  id: 4
  alu {
    vals {
      inputs {
        id {
          id: 32
        }
        name: "val"
      }
      output {
        id {
          id: 33
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
    }
    label: "Add"
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 3
      }
      name: "crd_outer-m"
    }
    index: "m"
    tensor: "X"
    format: "compressed"
    segsize: "2"
    crdsize: "G0_dim"
    sink: true
    label: "FiberWrite m: X0\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 14
      }
      name: "crd_out-n"
    }
    index: "n"
    tensor: "X"
    format: "compressed"
    segsize: "G0_dim+1"
    crdsize: "G0_dim*I1_dim"
    sink: true
    label: "FiberWrite n: X1\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 33
      }
      name: "val"
    }
    label: "FiberWrite Vals: X"
    crdsize: "1*G0_dim*I1_dim"
    tensor: "X"
    sink: true
  }
}

