name: "X=ss10,G=ss01,I=ss01,B=ss10,E=ss10,F=ss10,h=s0\""
operators {
  name: "fiberlookup"
  id: 78
  fiber_lookup {
    output_ref {
      id {
        id: 88
      }
    }
    output_crd {
      id {
        id: 1
      }
    }
    index: "j"
    tensor: "F"
    mode: 1
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup j: F1\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 76
  repeatsig {
    input_crd {
      id {
        id: 1
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 4
      }
    }
    label: "RepeatSignalGenerator j"
    index: "j"
  }
}
operators {
  name: "repeat"
  id: 74
  repeat {
    output_ref {
      id {
        id: 85
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat j: h"
    index: "j"
    root: true
    tensor: "h"
  }
}
operators {
  name: "repeat"
  id: 73
  repeat {
    output_ref {
      id {
        id: 84
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat j: E"
    index: "j"
    root: true
    tensor: "E"
  }
}
operators {
  name: "repeat"
  id: 72
  repeat {
    output_ref {
      id {
        id: 83
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat j: B"
    index: "j"
    root: true
    tensor: "B"
  }
}
operators {
  name: "repeat"
  id: 71
  repeat {
    output_ref {
      id {
        id: 82
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat j: I"
    index: "j"
    root: true
    tensor: "I"
  }
}
operators {
  name: "repeat"
  id: 70
  repeat {
    output_ref {
      id {
        id: 5
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat j: G"
    index: "j"
    root: true
    tensor: "G"
  }
}
operators {
  name: "fiberlookup"
  id: 69
  fiber_lookup {
    input_ref {
      id {
        id: 85
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 87
      }
    }
    output_crd {
      id {
        id: 86
      }
      name: "in-h"
    }
    index: "m"
    tensor: "h"
    format: "compressed"
    src: true
    label: "FiberLookup m: h0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 68
  fiber_lookup {
    input_ref {
      id {
        id: 5
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 81
      }
    }
    output_crd {
      id {
        id: 6
      }
      name: "in-G"
    }
    index: "m"
    tensor: "G"
    format: "compressed"
    src: true
    label: "FiberLookup m: G0\\ncompressed"
  }
}
operators {
  name: "union"
  id: 67
  joiner {
    join_type: UNION
    input_pairs {
      crd {
        id {
          id: 6
        }
        name: "crd_in-G"
      }
      ref {
        id {
          id: 81
        }
        name: "ref_in-G"
      }
    }
    input_pairs {
      crd {
        id {
          id: 86
        }
        name: "crd_in-h"
      }
      ref {
        id {
          id: 87
        }
        name: "ref_in-h"
      }
    }
    index: "m"
    label: "union m"
    output_ref1 {
      id {
        id: 77
      }
      name: "out-G"
    }
    output_ref2 {
      id {
        id: 78
      }
      name: "out-h"
    }
    output_crd {
      id {
        id: 7
      }
      name: "m"
    }
  }
}
operators {
  name: "repsiggen"
  id: 65
  repeatsig {
    input_crd {
      id {
        id: 7
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 11
      }
    }
    label: "RepeatSignalGenerator m"
    index: "m"
  }
}
operators {
  name: "repeat"
  id: 63
  repeat {
    input_ref {
      id {
        id: 88
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 74
      }
    }
    input_rep_sig {
      id {
        id: 11
      }
      name: "repsig"
    }
    label: "Repeat m: F"
    index: "m"
    tensor: "F"
  }
}
operators {
  name: "repeat"
  id: 62
  repeat {
    input_ref {
      id {
        id: 84
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 64
      }
    }
    input_rep_sig {
      id {
        id: 11
      }
      name: "repsig"
    }
    label: "Repeat m: E"
    index: "m"
    tensor: "E"
  }
}
operators {
  name: "repeat"
  id: 61
  repeat {
    input_ref {
      id {
        id: 83
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 62
      }
    }
    input_rep_sig {
      id {
        id: 11
      }
      name: "repsig"
    }
    label: "Repeat m: B"
    index: "m"
    tensor: "B"
  }
}
operators {
  name: "repeat"
  id: 60
  repeat {
    input_ref {
      id {
        id: 82
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 12
      }
    }
    input_rep_sig {
      id {
        id: 11
      }
      name: "repsig"
    }
    label: "Repeat m: I"
    index: "m"
    tensor: "I"
  }
}
operators {
  name: "fiberlookup"
  id: 59
  fiber_lookup {
    input_ref {
      id {
        id: 74
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 76
      }
    }
    output_crd {
      id {
        id: 75
      }
      name: "in-F"
    }
    index: "l"
    tensor: "F"
    format: "compressed"
    src: true
    label: "FiberLookup l: F0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 58
  fiber_lookup {
    input_ref {
      id {
        id: 64
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 73
      }
    }
    output_crd {
      id {
        id: 65
      }
      name: "in-E"
    }
    index: "l"
    tensor: "E"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup l: E1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 57
  joiner {
    input_pairs {
      crd {
        id {
          id: 65
        }
        name: "crd_in-E"
      }
      ref {
        id {
          id: 73
        }
        name: "ref_in-E"
      }
    }
    input_pairs {
      crd {
        id {
          id: 75
        }
        name: "crd_in-F"
      }
      ref {
        id {
          id: 76
        }
        name: "ref_in-F"
      }
    }
    index: "l"
    label: "intersect l"
    output_ref1 {
      id {
        id: 71
      }
      name: "out-E"
    }
    output_ref2 {
      id {
        id: 72
      }
      name: "out-F"
    }
    output_crd {
      id {
        id: 66
      }
      name: "l"
    }
  }
}
operators {
  name: "repsiggen"
  id: 55
  repeatsig {
    input_crd {
      id {
        id: 66
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 67
      }
    }
    label: "RepeatSignalGenerator l"
    index: "l"
  }
}
operators {
  name: "repeat"
  id: 53
  repeat {
    input_ref {
      id {
        id: 62
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 63
      }
    }
    input_rep_sig {
      id {
        id: 67
      }
      name: "repsig"
    }
    label: "Repeat l: B"
    index: "l"
    tensor: "B"
  }
}
operators {
  name: "repeat"
  id: 52
  repeat {
    input_ref {
      id {
        id: 12
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 13
      }
    }
    input_rep_sig {
      id {
        id: 67
      }
      name: "repsig"
    }
    label: "Repeat l: I"
    index: "l"
    tensor: "I"
  }
}
operators {
  name: "repeat"
  id: 51
  repeat {
    input_ref {
      id {
        id: 77
      }
      name: "ref_out-G"
    }
    output_ref {
      id {
        id: 68
      }
    }
    input_rep_sig {
      id {
        id: 67
      }
      name: "repsig"
    }
    label: "Repeat l: G"
    index: "l"
    tensor: "G"
  }
}
operators {
  name: "fiberlookup"
  id: 50
  fiber_lookup {
    input_ref {
      id {
        id: 13
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 61
      }
    }
    output_crd {
      id {
        id: 14
      }
      name: "in-I"
    }
    index: "n"
    tensor: "I"
    format: "compressed"
    src: true
    label: "FiberLookup n: I0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 49
  fiber_lookup {
    input_ref {
      id {
        id: 68
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 70
      }
    }
    output_crd {
      id {
        id: 69
      }
      name: "in-G"
    }
    index: "n"
    tensor: "G"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup n: G1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 48
  joiner {
    input_pairs {
      crd {
        id {
          id: 14
        }
        name: "crd_in-I"
      }
      ref {
        id {
          id: 61
        }
        name: "ref_in-I"
      }
    }
    input_pairs {
      crd {
        id {
          id: 69
        }
        name: "crd_in-G"
      }
      ref {
        id {
          id: 70
        }
        name: "ref_in-G"
      }
    }
    index: "n"
    label: "intersect n"
    output_ref1 {
      id {
        id: 60
      }
      name: "out-I"
    }
    output_ref2 {
      id {
        id: 59
      }
      name: "out-G"
    }
    output_crd {
      id {
        id: 15
      }
      name: "n"
    }
  }
}
operators {
  name: "repsiggen"
  id: 46
  repeatsig {
    input_crd {
      id {
        id: 15
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 21
      }
    }
    label: "RepeatSignalGenerator n"
    index: "n"
  }
}
operators {
  name: "repeat"
  id: 44
  repeat {
    input_ref {
      id {
        id: 72
      }
      name: "ref_out-F"
    }
    output_ref {
      id {
        id: 58
      }
    }
    input_rep_sig {
      id {
        id: 21
      }
      name: "repsig"
    }
    label: "Repeat n: F"
    index: "n"
    tensor: "F"
  }
}
operators {
  name: "repeat"
  id: 43
  repeat {
    input_ref {
      id {
        id: 71
      }
      name: "ref_out-E"
    }
    output_ref {
      id {
        id: 55
      }
    }
    input_rep_sig {
      id {
        id: 21
      }
      name: "repsig"
    }
    label: "Repeat n: E"
    index: "n"
    tensor: "E"
  }
}
operators {
  name: "repeat"
  id: 42
  repeat {
    input_ref {
      id {
        id: 63
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 22
      }
    }
    input_rep_sig {
      id {
        id: 21
      }
      name: "repsig"
    }
    label: "Repeat n: B"
    index: "n"
    tensor: "B"
  }
}
operators {
  name: "fiberlookup"
  id: 41
  fiber_lookup {
    input_ref {
      id {
        id: 55
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 57
      }
    }
    output_crd {
      id {
        id: 56
      }
      name: "in-E"
    }
    index: "k"
    tensor: "E"
    format: "compressed"
    src: true
    label: "FiberLookup k: E0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 40
  fiber_lookup {
    input_ref {
      id {
        id: 22
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 54
      }
    }
    output_crd {
      id {
        id: 23
      }
      name: "in-B"
    }
    index: "k"
    tensor: "B"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup k: B1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 39
  joiner {
    input_pairs {
      crd {
        id {
          id: 23
        }
        name: "crd_in-B"
      }
      ref {
        id {
          id: 54
        }
        name: "ref_in-B"
      }
    }
    input_pairs {
      crd {
        id {
          id: 56
        }
        name: "crd_in-E"
      }
      ref {
        id {
          id: 57
        }
        name: "ref_in-E"
      }
    }
    index: "k"
    label: "intersect k"
    output_ref1 {
      id {
        id: 50
      }
      name: "out-B"
    }
    output_ref2 {
      id {
        id: 53
      }
      name: "out-E"
    }
    output_crd {
      id {
        id: 24
      }
      name: "k"
    }
  }
}
operators {
  name: "repsiggen"
  id: 37
  repeatsig {
    input_crd {
      id {
        id: 24
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 28
      }
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 35
  repeat {
    input_ref {
      id {
        id: 58
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 49
      }
    }
    input_rep_sig {
      id {
        id: 28
      }
      name: "repsig"
    }
    label: "Repeat k: F"
    index: "k"
    tensor: "F"
  }
}
operators {
  name: "repeat"
  id: 34
  repeat {
    input_ref {
      id {
        id: 60
      }
      name: "ref_out-I"
    }
    output_ref {
      id {
        id: 36
      }
    }
    input_rep_sig {
      id {
        id: 28
      }
      name: "repsig"
    }
    label: "Repeat k: I"
    index: "k"
    tensor: "I"
  }
}
operators {
  name: "repeat"
  id: 33
  repeat {
    input_ref {
      id {
        id: 59
      }
      name: "ref_out-G"
    }
    output_ref {
      id {
        id: 29
      }
    }
    input_rep_sig {
      id {
        id: 28
      }
      name: "repsig"
    }
    label: "Repeat k: G"
    index: "k"
    tensor: "G"
  }
}
operators {
  name: "fiberlookup"
  id: 32
  fiber_lookup {
    input_ref {
      id {
        id: 50
      }
      name: "ref_out-B"
    }
    output_ref {
      id {
        id: 52
      }
    }
    output_crd {
      id {
        id: 51
      }
      name: "in-B"
    }
    index: "i"
    tensor: "B"
    format: "compressed"
    src: true
    label: "FiberLookup i: B0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 31
  fiber_lookup {
    input_ref {
      id {
        id: 36
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 48
      }
    }
    output_crd {
      id {
        id: 37
      }
      name: "in-I"
    }
    index: "i"
    tensor: "I"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup i: I1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 30
  joiner {
    input_pairs {
      crd {
        id {
          id: 37
        }
        name: "crd_in-I"
      }
      ref {
        id {
          id: 48
        }
        name: "ref_in-I"
      }
    }
    input_pairs {
      crd {
        id {
          id: 51
        }
        name: "crd_in-B"
      }
      ref {
        id {
          id: 52
        }
        name: "ref_in-B"
      }
    }
    index: "i"
    label: "intersect i"
    output_ref1 {
      id {
        id: 44
      }
      name: "out-I"
    }
    output_ref2 {
      id {
        id: 46
      }
      name: "out-B"
    }
    output_crd {
      id {
        id: 38
      }
      name: "i"
    }
  }
}
operators {
  name: "repsiggen"
  id: 28
  repeatsig {
    input_crd {
      id {
        id: 38
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 39
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 26
  repeat {
    input_ref {
      id {
        id: 49
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 42
      }
    }
    input_rep_sig {
      id {
        id: 39
      }
      name: "repsig"
    }
    label: "Repeat i: F"
    index: "i"
    tensor: "F"
  }
}
operators {
  name: "repeat"
  id: 25
  repeat {
    input_ref {
      id {
        id: 53
      }
      name: "ref_out-E"
    }
    output_ref {
      id {
        id: 40
      }
    }
    input_rep_sig {
      id {
        id: 39
      }
      name: "repsig"
    }
    label: "Repeat i: E"
    index: "i"
    tensor: "E"
  }
}
operators {
  name: "repeat"
  id: 24
  repeat {
    input_ref {
      id {
        id: 29
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 30
      }
    }
    input_rep_sig {
      id {
        id: 39
      }
      name: "repsig"
    }
    label: "Repeat i: G"
    index: "i"
    tensor: "G"
  }
}
operators {
  name: "crddrop"
  id: 23
  coord_drop {
    input_inner_crd {
      id {
        id: 38
      }
      name: "crd_i"
    }
    input_outer_crd {
      id {
        id: 24
      }
      name: "crd_k"
    }
    output_inner_crd {
      id {
        id: 26
      }
      name: "inner-i"
    }
    output_outer_crd {
      id {
        id: 25
      }
      name: "outer-k"
    }
    inner_crd: "i"
    outer_crd: "k"
    label: "CrdDrop k,i"
  }
}
operators {
  name: "crddrop"
  id: 22
  coord_drop {
    input_inner_crd {
      id {
        id: 25
      }
      name: "crd_outer-k"
    }
    input_outer_crd {
      id {
        id: 15
      }
      name: "crd_n"
    }
    output_inner_crd {
      id {
        id: 19
      }
      name: "inner-k"
    }
    output_outer_crd {
      id {
        id: 16
      }
      name: "outer-n"
    }
    inner_crd: "k"
    outer_crd: "n"
    label: "CrdDrop n,k"
  }
}
operators {
  name: "crddrop"
  id: 21
  coord_drop {
    input_inner_crd {
      id {
        id: 16
      }
      name: "crd_outer-n"
    }
    input_outer_crd {
      id {
        id: 66
      }
      name: "crd_l"
    }
    output_inner_crd {
      id {
        id: 18
      }
      name: "inner-n"
    }
    output_outer_crd {
      id {
        id: 17
      }
      name: "outer-l"
    }
    inner_crd: "n"
    outer_crd: "l"
    label: "CrdDrop l,n"
  }
}
operators {
  name: "crddrop"
  id: 20
  coord_drop {
    input_inner_crd {
      id {
        id: 17
      }
      name: "crd_outer-l"
    }
    input_outer_crd {
      id {
        id: 7
      }
      name: "crd_m"
    }
    output_inner_crd {
      id {
        id: 9
      }
      name: "inner-l"
    }
    output_outer_crd {
      id {
        id: 8
      }
      name: "outer-m"
    }
    inner_crd: "l"
    outer_crd: "m"
    label: "CrdDrop m,l"
  }
}
operators {
  name: "crddrop"
  id: 19
  coord_drop {
    input_inner_crd {
      id {
        id: 8
      }
      name: "crd_outer-m"
    }
    input_outer_crd {
      id {
        id: 1
      }
      name: "crd_j"
    }
    output_inner_crd {
      id {
        id: 3
      }
      name: "inner-m"
    }
    output_outer_crd {
      id {
        id: 2
      }
      name: "outer-j"
    }
    inner_crd: "m"
    outer_crd: "j"
    label: "CrdDrop j,m"
  }
}
operators {
  name: "arrayvals"
  id: 18
  array {
    tensor: "h"
    input_ref {
      id {
        id: 78
      }
      name: "ref_out-h"
    }
    output_val {
      id {
        id: 79
      }
      name: "val"
    }
    label: "Array Vals: h"
  }
}
operators {
  name: "arrayvals"
  id: 17
  array {
    tensor: "F"
    input_ref {
      id {
        id: 42
      }
      name: "ref"
    }
    output_val {
      id {
        id: 43
      }
      name: "val"
    }
    label: "Array Vals: F"
  }
}
operators {
  name: "arrayvals"
  id: 16
  array {
    tensor: "E"
    input_ref {
      id {
        id: 40
      }
      name: "ref"
    }
    output_val {
      id {
        id: 41
      }
      name: "val"
    }
    label: "Array Vals: E"
  }
}
operators {
  name: "arrayvals"
  id: 15
  array {
    tensor: "B"
    input_ref {
      id {
        id: 46
      }
      name: "ref_out-B"
    }
    output_val {
      id {
        id: 47
      }
      name: "val"
    }
    label: "Array Vals: B"
  }
}
operators {
  name: "arrayvals"
  id: 14
  array {
    tensor: "I"
    input_ref {
      id {
        id: 44
      }
      name: "ref_out-I"
    }
    output_val {
      id {
        id: 45
      }
      name: "val"
    }
    label: "Array Vals: I"
  }
}
operators {
  name: "arrayvals"
  id: 13
  array {
    tensor: "G"
    input_ref {
      id {
        id: 30
      }
      name: "ref"
    }
    output_val {
      id {
        id: 31
      }
      name: "val"
    }
    label: "Array Vals: G"
  }
}
operators {
  name: "mul"
  id: 12
  alu {
    vals {
      inputs {
        id {
          id: 31
        }
        name: "val"
      }
      inputs {
        id {
          id: 45
        }
        name: "val"
      }
      output {
        id {
          id: 32
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 11
  alu {
    vals {
      inputs {
        id {
          id: 32
        }
        name: "val"
      }
      inputs {
        id {
          id: 47
        }
        name: "val"
      }
      output {
        id {
          id: 33
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 10
  alu {
    vals {
      inputs {
        id {
          id: 33
        }
        name: "val"
      }
      inputs {
        id {
          id: 41
        }
        name: "val"
      }
      output {
        id {
          id: 34
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 9
  alu {
    vals {
      inputs {
        id {
          id: 34
        }
        name: "val"
      }
      inputs {
        id {
          id: 43
        }
        name: "val"
      }
      output {
        id {
          id: 35
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "spaccumulator"
  id: 8
  spacc {
    input_inner_crd {
      id {
        id: 26
      }
      name: "crd_inner-i"
    }
    input_val {
      id {
        id: 35
      }
      name: "val"
    }
    output_val {
      id {
        id: 27
      }
    }
    inner_crd: "i"
    outer_crds: "k"
    outer_crds: "n"
    outer_crds: "l"
    outer_crds: "i"
    outer_crds: "k"
    outer_crds: "i"
    label: "SparseAccumulator 0 "
  }
}
operators {
  name: "spaccumulator"
  id: 7
  spacc {
    input_outer_crds {
      id {
        id: 19
      }
      name: "crd_inner-k"
    }
    output_val {
      id {
        id: 20
      }
    }
    order: 1
    inner_crd: "i"
    outer_crds: "k"
    outer_crds: "n"
    outer_crds: "l"
    outer_crds: "i"
    outer_crds: "k"
    label: "SparseAccumulator 1 "
  }
}
operators {
  name: "spaccumulator"
  id: 5
  spacc {
    input_outer_crds {
      id {
        id: 9
      }
      name: "crd_inner-l"
    }
    input_outer_crds {
      id {
        id: 18
      }
      name: "crd_inner-n"
    }
    output_val {
      id {
        id: 10
      }
    }
    order: 3
    inner_crd: "i"
    outer_crds: "k"
    outer_crds: "n"
    outer_crds: "l"
    label: "SparseAccumulator 3 "
  }
}
operators {
  name: "add"
  id: 4
  alu {
    vals {
      inputs {
        id {
          id: 79
        }
        name: "val"
      }
      output {
        id {
          id: 80
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
    }
    label: "Add"
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 2
      }
      name: "crd_outer-j"
    }
    index: "j"
    tensor: "X"
    format: "compressed"
    segsize: "2"
    crdsize: "F1_dim"
    sink: true
    label: "FiberWrite j: X1\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 3
      }
      name: "crd_inner-m"
    }
    index: "m"
    tensor: "X"
    format: "compressed"
    segsize: "F1_dim+1"
    crdsize: "F1_dim*G0_dim"
    sink: true
    label: "FiberWrite m: X0\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 80
      }
      name: "val"
    }
    label: "FiberWrite Vals: X"
    crdsize: "1*F1_dim*G0_dim"
    tensor: "X"
    sink: true
  }
}

