name: "B=ss01,E=ss01,F=ss10\""
operators {
  name: "fiberlookup"
  id: 20
  fiber_lookup {
    output_ref {
      id {
        id: 22
      }
    }
    output_crd {
      id {
        id: 1
      }
    }
    index: "i"
    tensor: "E"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup i: E0\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 18
  repeatsig {
    input_crd {
      id {
        id: 1
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 4
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 17
  repeat {
    output_ref {
      id {
        id: 5
      }
    }
    input_rep_sig {
      id {
        id: 4
      }
      name: "repsig"
    }
    label: "Repeat i: F"
    index: "i"
    root: true
    tensor: "F"
  }
}
operators {
  name: "fiberlookup"
  id: 16
  fiber_lookup {
    input_ref {
      id {
        id: 5
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 19
      }
    }
    output_crd {
      id {
        id: 6
      }
    }
    index: "k"
    tensor: "F"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup k: F1\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 14
  repeatsig {
    input_crd {
      id {
        id: 6
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 8
      }
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 13
  repeat {
    input_ref {
      id {
        id: 22
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 9
      }
    }
    input_rep_sig {
      id {
        id: 8
      }
      name: "repsig"
    }
    label: "Repeat k: E"
    index: "k"
    tensor: "E"
  }
}
operators {
  name: "fiberlookup"
  id: 12
  fiber_lookup {
    input_ref {
      id {
        id: 19
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 21
      }
    }
    output_crd {
      id {
        id: 20
      }
      name: "in-F"
    }
    index: "l"
    tensor: "F"
    format: "compressed"
    src: true
    label: "FiberLookup l: F0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 11
  fiber_lookup {
    input_ref {
      id {
        id: 9
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 18
      }
    }
    output_crd {
      id {
        id: 10
      }
      name: "in-E"
    }
    index: "l"
    tensor: "E"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup l: E1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 10
  joiner {
    input_pairs {
      crd {
        id {
          id: 10
        }
        name: "crd_in-E"
      }
      ref {
        id {
          id: 18
        }
        name: "ref_in-E"
      }
    }
    input_pairs {
      crd {
        id {
          id: 20
        }
        name: "crd_in-F"
      }
      ref {
        id {
          id: 21
        }
        name: "ref_in-F"
      }
    }
    index: "l"
    label: "intersect l"
    output_ref1 {
      id {
        id: 12
      }
      name: "out-E"
    }
    output_ref2 {
      id {
        id: 16
      }
      name: "out-F"
    }
    output_crd {
      id {
        id: 11
      }
      name: "in-l"
    }
  }
}
operators {
  name: "crddrop"
  id: 9
  coord_drop {
    input_inner_crd {
      id {
        id: 11
      }
      name: "crd_in-l"
    }
    input_outer_crd {
      id {
        id: 6
      }
      name: "crd_k"
    }
    output_outer_crd {
      id {
        id: 7
      }
      name: "outer-k"
    }
    inner_crd: "l"
    outer_crd: "k"
    label: "CrdDrop k,l"
  }
}
operators {
  name: "crddrop"
  id: 8
  coord_drop {
    input_inner_crd {
      id {
        id: 7
      }
      name: "crd_outer-k"
    }
    input_outer_crd {
      id {
        id: 1
      }
      name: "crd_i"
    }
    output_inner_crd {
      id {
        id: 3
      }
      name: "inner-k"
    }
    output_outer_crd {
      id {
        id: 2
      }
      name: "outer-i"
    }
    inner_crd: "k"
    outer_crd: "i"
    label: "CrdDrop i,k"
  }
}
operators {
  name: "arrayvals"
  id: 7
  array {
    tensor: "F"
    input_ref {
      id {
        id: 16
      }
      name: "ref_out-F"
    }
    output_val {
      id {
        id: 17
      }
      name: "val"
    }
    label: "Array Vals: F"
  }
}
operators {
  name: "arrayvals"
  id: 6
  array {
    tensor: "E"
    input_ref {
      id {
        id: 12
      }
      name: "ref_out-E"
    }
    output_val {
      id {
        id: 13
      }
      name: "val"
    }
    label: "Array Vals: E"
  }
}
operators {
  name: "mul"
  id: 5
  alu {
    vals {
      inputs {
        id {
          id: 13
        }
        name: "val"
      }
      inputs {
        id {
          id: 17
        }
        name: "val"
      }
      output {
        id {
          id: 14
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "reduce"
  id: 4
  reduce {
    input_val {
      id {
        id: 14
      }
      name: "val"
    }
    output_val {
      id {
        id: 15
      }
      name: "reduce_val"
    }
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 2
      }
      name: "crd_outer-i"
    }
    index: "i"
    tensor: "B"
    format: "compressed"
    segsize: "2"
    crdsize: "E0_dim"
    sink: true
    label: "FiberWrite i: B0\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 3
      }
      name: "crd_inner-k"
    }
    index: "k"
    tensor: "B"
    format: "compressed"
    segsize: "E0_dim+1"
    crdsize: "E0_dim*F1_dim"
    sink: true
    label: "FiberWrite k: B1\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 15
      }
      name: "val"
    }
    label: "FiberWrite Vals: B"
    crdsize: "1*E0_dim*F1_dim"
    tensor: "B"
    sink: true
  }
}

