name: "X=ss01,B=ss01,C=dd01,D=dd10\""
operators {
  name: "fiberlookup"
  id: 30
  fiber_lookup {
    output_ref {
      id {
        id: 36
      }
    }
    output_crd {
      id {
        id: 35
      }
      name: "in-C"
    }
    index: "i"
    tensor: "C"
    format: "dense"
    src: true
    root: true
    label: "FiberLookup i: C0\\ndense"
  }
}
operators {
  name: "fiberlookup"
  id: 29
  fiber_lookup {
    output_ref {
      id {
        id: 34
      }
    }
    output_crd {
      id {
        id: 1
      }
      name: "in-B"
    }
    index: "i"
    tensor: "B"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup i: B0\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 28
  joiner {
    input_pairs {
      crd {
        id {
          id: 1
        }
        name: "crd_in-B"
      }
      ref {
        id {
          id: 34
        }
        name: "ref_in-B"
      }
    }
    input_pairs {
      crd {
        id {
          id: 35
        }
        name: "crd_in-C"
      }
      ref {
        id {
          id: 36
        }
        name: "ref_in-C"
      }
    }
    index: "i"
    label: "intersect i"
    output_ref1 {
      id {
        id: 5
      }
      name: "out-B"
    }
    output_ref2 {
      id {
        id: 33
      }
      name: "out-C"
    }
    output_crd {
      id {
        id: 2
      }
      name: "i"
    }
  }
}
operators {
  name: "broadcast"
  id: 27
  broadcast {
    input {
      name: "crd_i"
    }
    label: "broadcast"
  }
}
operators {
  name: "repsiggen"
  id: 26
  repeatsig {
    input_crd {
      id {
        id: 5
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 6
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 25
  repeat {
    output_ref {
      id {
        id: 7
      }
    }
    input_rep_sig {
      id {
        id: 6
      }
      name: "repsig"
    }
    label: "Repeat i: D"
    index: "i"
    root: true
    tensor: "D"
  }
}
operators {
  name: "fiberlookup"
  id: 24
  fiber_lookup {
    input_ref {
      id {
        id: 7
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 30
      }
    }
    output_crd {
      id {
        id: 8
      }
      name: "in-D"
    }
    index: "j"
    tensor: "D"
    mode: 1
    format: "dense"
    src: true
    label: "FiberLookup j: D1\\ndense"
  }
}
operators {
  name: "fiberlookup"
  id: 23
  fiber_lookup {
    input_ref {
      id {
        id: 5
      }
      name: "ref_out-B"
    }
    output_ref {
      id {
        id: 32
      }
    }
    output_crd {
      id {
        id: 31
      }
      name: "in-B"
    }
    index: "j"
    tensor: "B"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup j: B1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 22
  joiner {
    input_pairs {
      crd {
        id {
          id: 8
        }
        name: "crd_in-D"
      }
      ref {
        id {
          id: 30
        }
        name: "ref_in-D"
      }
    }
    input_pairs {
      crd {
        id {
          id: 31
        }
        name: "crd_in-B"
      }
      ref {
        id {
          id: 32
        }
        name: "ref_in-B"
      }
    }
    index: "j"
    label: "intersect j"
    output_ref1 {
      id {
        id: 11
      }
      name: "out-B"
    }
    output_ref2 {
      id {
        id: 27
      }
      name: "out-D"
    }
    output_crd {
      id {
        id: 9
      }
      name: "j"
    }
  }
}
operators {
  name: "broadcast"
  id: 21
  broadcast {
    input {
      name: "crd_j"
    }
    label: "broadcast"
  }
}
operators {
  name: "repsiggen"
  id: 20
  repeatsig {
    input_crd {
      id {
        id: 11
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 12
      }
    }
    label: "RepeatSignalGenerator j"
    index: "j"
  }
}
operators {
  name: "repeat"
  id: 19
  repeat {
    input_ref {
      id {
        id: 33
      }
      name: "ref_out-C"
    }
    output_ref {
      id {
        id: 13
      }
    }
    input_rep_sig {
      id {
        id: 12
      }
      name: "repsig"
    }
    label: "Repeat j: C"
    index: "j"
    tensor: "C"
  }
}
operators {
  name: "fiberlookup"
  id: 18
  fiber_lookup {
    input_ref {
      id {
        id: 27
      }
      name: "ref_out-D"
    }
    output_ref {
      id {
        id: 29
      }
    }
    output_crd {
      id {
        id: 28
      }
      name: "in-D"
    }
    index: "k"
    tensor: "D"
    format: "dense"
    src: true
    label: "FiberLookup k: D0\\ndense"
  }
}
operators {
  name: "fiberlookup"
  id: 17
  fiber_lookup {
    input_ref {
      id {
        id: 13
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 26
      }
    }
    output_crd {
      id {
        id: 14
      }
      name: "in-C"
    }
    index: "k"
    tensor: "C"
    mode: 1
    format: "dense"
    src: true
    label: "FiberLookup k: C1\\ndense"
  }
}
operators {
  name: "intersect"
  id: 16
  joiner {
    input_pairs {
      crd {
        id {
          id: 14
        }
        name: "crd_in-C"
      }
      ref {
        id {
          id: 26
        }
        name: "ref_in-C"
      }
    }
    input_pairs {
      crd {
        id {
          id: 28
        }
        name: "crd_in-D"
      }
      ref {
        id {
          id: 29
        }
        name: "ref_in-D"
      }
    }
    index: "k"
    label: "intersect k"
    output_ref1 {
      id {
        id: 16
      }
      name: "out-C"
    }
    output_ref2 {
      id {
        id: 24
      }
      name: "out-D"
    }
    output_crd {
      id {
        id: 15
      }
      name: "k"
    }
  }
}
operators {
  name: "broadcast"
  id: 15
  broadcast {
    input {
      name: "crd_k"
    }
    label: "broadcast"
  }
}
operators {
  name: "repsiggen"
  id: 14
  repeatsig {
    input_crd {
      id {
        id: 16
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 17
      }
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 13
  repeat {
    input_ref {
      id {
        id: 11
      }
      name: "ref_out-B"
    }
    output_ref {
      id {
        id: 18
      }
    }
    input_rep_sig {
      id {
        id: 17
      }
      name: "repsig"
    }
    label: "Repeat k: B"
    index: "k"
    tensor: "B"
  }
}
operators {
  name: "crddrop"
  id: 12
  coord_drop {
    input_inner_crd {
      id {
        id: 15
      }
      name: "crd_k"
    }
    input_outer_crd {
      id {
        id: 9
      }
      name: "crd_j"
    }
    output_outer_crd {
      id {
        id: 10
      }
      name: "outer-j"
    }
    inner_crd: "k"
    outer_crd: "j"
    label: "CrdDrop j,k"
  }
}
operators {
  name: "crddrop"
  id: 11
  coord_drop {
    input_inner_crd {
      id {
        id: 10
      }
      name: "crd_outer-j"
    }
    input_outer_crd {
      id {
        id: 2
      }
      name: "crd_i"
    }
    output_inner_crd {
      id {
        id: 4
      }
      name: "inner-j"
    }
    output_outer_crd {
      id {
        id: 3
      }
      name: "outer-i"
    }
    inner_crd: "j"
    outer_crd: "i"
    label: "CrdDrop i,j"
  }
}
operators {
  name: "arrayvals"
  id: 10
  array {
    tensor: "D"
    input_ref {
      id {
        id: 24
      }
      name: "ref_out-D"
    }
    output_val {
      id {
        id: 25
      }
      name: "val"
    }
    label: "Array Vals: D"
  }
}
operators {
  name: "arrayvals"
  id: 9
  array {
    tensor: "C"
    input_ref {
      id {
        id: 16
      }
      name: "ref_out-C"
    }
    output_val {
      id {
        id: 23
      }
      name: "val"
    }
    label: "Array Vals: C"
  }
}
operators {
  name: "arrayvals"
  id: 8
  array {
    tensor: "B"
    input_ref {
      id {
        id: 18
      }
      name: "ref"
    }
    output_val {
      id {
        id: 19
      }
      name: "val"
    }
    label: "Array Vals: B"
  }
}
operators {
  name: "mul"
  id: 7
  alu {
    vals {
      inputs {
        id {
          id: 19
        }
        name: "val"
      }
      inputs {
        id {
          id: 23
        }
        name: "val"
      }
      output {
        id {
          id: 20
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 6
  alu {
    vals {
      inputs {
        id {
          id: 20
        }
        name: "val"
      }
      inputs {
        id {
          id: 25
        }
        name: "val"
      }
      output {
        id {
          id: 21
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "reduce"
  id: 5
  reduce {
    input_val {
      id {
        id: 21
      }
      name: "val"
    }
    output_val {
      id {
        id: 22
      }
      name: "reduce_val"
    }
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 3
      }
      name: "crd_outer-i"
    }
    index: "i"
    tensor: "X"
    format: "compressed"
    segsize: "2"
    crdsize: "B0_dim"
    sink: true
    label: "FiberWrite i: X0\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 4
      }
      name: "crd_inner-j"
    }
    index: "j"
    tensor: "X"
    format: "compressed"
    segsize: "B0_dim+1"
    crdsize: "B0_dim*B1_dim"
    sink: true
    label: "FiberWrite j: X1\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 22
      }
      name: "val"
    }
    label: "FiberWrite Vals: X"
    crdsize: "1*B0_dim*B1_dim"
    tensor: "X"
    sink: true
  }
}

