name: "X=ssss0123,Q=ssss0213,K=ssss0213\""
operators {
  name: "fiberlookup"
  id: 30
  fiber_lookup {
    output_ref {
      id {
        id: 1038
      }
      name: "in-Q"
    }
    output_crd {
      id {
      }
      name: "in-Q"
    }
    index: "i"
    tensor: "Q"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup i: Q0\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 29
  joiner {
    input_pairs {
      crd {
        id {
          id: 1000
        }
        name: "crd_in-Q"
      }
      ref {
        id {
          id: 1041
        }
        name: "ref_in-Q"
      }
    }
    input_pairs {
      crd {
        id {
          id: 1042
        }
        name: "crd_in-K"
      }
      ref {
        id {
          id: 1043
        }
        name: "ref_in-K"
      }
    }
    index: "i"
    label: "intersect i"
    output_ref1 {
      id {
      }
      name: "out-Q"
    }
    output_ref2 {
      id {
      }
      name: "out-K"
    }
    output_crd {
      id {
      }
      name: "in-i"
    }
  }
}
operators {
  name: "crddrop"
  id: 11
  coord_drop {
    input_inner_crd {
      id {
        id: 1007
      }
      name: "crd_outer-j"
    }
    input_outer_crd {
      id {
        id: 1001
      }
      name: "crd_in-i"
    }
    output_inner_crd {
      name: "inner-j"
    }
    output_outer_crd {
      id {
      }
      name: "outer-i"
    }
    inner_crd: "j"
    outer_crd: "i"
    label: "CrdDrop i,j"
  }
}
operators {
  name: "fiberwrite"
  id: 5
  fiber_write {
    input_crd {
      id {
        id: 1002
      }
      name: "crd_outer-i"
    }
    index: "i"
    tensor: "X"
    format: "compressed"
    segsize: "2"
    crdsize: "Q0_dim"
    sink: true
    label: "FiberWrite i: X0\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 4
  fiber_write {
    input_crd {
      id {
        id: 1003
      }
      name: "crd_inner-j"
    }
    index: "j"
    tensor: "X"
    format: "compressed"
    segsize: "Q0_dim+1"
    crdsize: "Q0_dim*Q2_dim"
    sink: true
    label: "FiberWrite j: X1\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 27
  fiber_lookup {
    input_ref {
      id {
        id: 1004
      }
      name: "ref_out-Q"
    }
    output_ref {
      id {
        id: 1036
      }
      name: "in-Q"
    }
    output_crd {
      id {
      }
      name: "in-Q"
    }
    index: "j"
    tensor: "Q"
    mode: 2
    format: "compressed"
    src: true
    label: "FiberLookup j: Q2\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 26
  joiner {
    input_pairs {
      crd {
        id {
          id: 1005
        }
        name: "crd_in-Q"
      }
      ref {
        id {
          id: 1037
        }
        name: "ref_in-Q"
      }
    }
    input_pairs {
      crd {
        id {
          id: 1039
        }
        name: "crd_in-K"
      }
      ref {
        id {
          id: 1040
        }
        name: "ref_in-K"
      }
    }
    index: "j"
    label: "intersect j"
    output_ref1 {
      id {
      }
      name: "out-Q"
    }
    output_ref2 {
      id {
        id: 1016
      }
      name: "out-K"
    }
    output_crd {
      id {
      }
      name: "in-j"
    }
  }
}
operators {
  name: "crddrop"
  id: 12
  coord_drop {
    input_inner_crd {
      id {
        id: 1012
      }
      name: "crd_outer-k"
    }
    input_outer_crd {
      id {
        id: 1006
      }
      name: "crd_in-j"
    }
    output_inner_crd {
      name: "inner-k"
    }
    output_outer_crd {
      id {
      }
      name: "outer-j"
    }
    inner_crd: "k"
    outer_crd: "j"
    label: "CrdDrop j,k"
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 1008
      }
      name: "crd_inner-k"
    }
    index: "k"
    tensor: "X"
    format: "compressed"
    segsize: "Q0_dim*Q2_dim+1"
    crdsize: "Q0_dim*Q2_dim*Q1_dim"
    sink: true
    label: "FiberWrite k: X2\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 25
  fiber_lookup {
    input_ref {
      id {
        id: 1009
      }
      name: "ref_out-Q"
    }
    output_ref {
      id {
        id: 1022
      }
    }
    output_crd {
      id {
      }
    }
    index: "k"
    tensor: "Q"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup k: Q1\\ncompressed"
  }
}
operators {
  name: "broadcast"
  id: 24
  broadcast {
    input {
      id {
        id: 1010
      }
      name: "crd"
    }
    outputs {
      id {
      }
      name: "k"
    }
    outputs {
      id {
      }
    }
    label: "broadcast"
  }
}
operators {
  name: "crddrop"
  id: 13
  coord_drop {
    input_inner_crd {
      id {
        id: 1019
      }
      name: "crd_outer-l"
    }
    input_outer_crd {
      id {
        id: 1011
      }
      name: "crd_k"
    }
    output_inner_crd {
      name: "inner-l"
    }
    output_outer_crd {
      id {
      }
      name: "outer-k"
    }
    inner_crd: "l"
    outer_crd: "k"
    label: "CrdDrop k,l"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 1013
      }
      name: "crd_inner-l"
    }
    index: "l"
    tensor: "X"
    format: "compressed"
    segsize: "Q0_dim*Q2_dim*Q1_dim+1"
    crdsize: "Q0_dim*Q2_dim*Q1_dim*K1_dim"
    sink: true
    label: "FiberWrite l: X3\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 23
  repeatsig {
    input_crd {
      id {
        id: 1014
      }
      name: "crd"
    }
    output_rep_sig {
      id {
      }
      name: "repsig"
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 22
  repeat {
    input_ref {
      id {
        id: 1036
      }
      name: "ref_out-K"
    }
    output_ref {
      id {
      }
      name: "ref"
    }
    input_rep_sig {
      id {
        id: 1015
      }
      name: "repsig"
    }
    label: "Repeat k: K"
    index: "k"
    tensor: "K"
  }
}
operators {
  name: "fiberlookup"
  id: 21
  fiber_lookup {
    input_ref {
      id {
        id: 1016
      }
      name: "ref"
    }
    output_ref {
      id {
      }
    }
    output_crd {
      id {
      }
    }
    index: "l"
    tensor: "K"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup l: K1\\ncompressed"
  }
}
operators {
  name: "broadcast"
  id: 20
  broadcast {
    input {
      id {
        id: 1017
      }
      name: "crd"
    }
    outputs {
      id {
      }
      name: "l"
    }
    outputs {
      id {
      }
    }
    label: "broadcast"
  }
}
operators {
  name: "crddrop"
  id: 14
  coord_drop {
    input_inner_crd {
      id {
        id: 1024
      }
      name: "crd_in-m"
    }
    input_outer_crd {
      id {
        id: 1018
      }
      name: "crd_l"
    }
    output_outer_crd {
      id {
        id: 1013
      }
      name: "outer-l"
    }
    inner_crd: "m"
    outer_crd: "l"
    label: "CrdDrop l,m"
  }
}
operators {
  name: "repsiggen"
  id: 19
  repeatsig {
    input_crd {
      id {
        id: 1020
      }
      name: "crd"
    }
    output_rep_sig {
      id {
      }
      name: "repsig"
    }
    label: "RepeatSignalGenerator l"
    index: "l"
  }
}
operators {
  name: "repeat"
  id: 18
  repeat {
    input_ref {
      id {
        id: 1035
      }
      name: "ref"
    }
    output_ref {
      id {
      }
      name: "ref"
    }
    input_rep_sig {
      id {
        id: 1021
      }
      name: "repsig"
    }
    label: "Repeat l: Q"
    index: "l"
    tensor: "Q"
  }
}
operators {
  name: "fiberlookup"
  id: 16
  fiber_lookup {
    input_ref {
      id {
        id: 1022
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 1029
      }
      name: "in-Q"
    }
    output_crd {
      id {
      }
      name: "in-Q"
    }
    index: "m"
    tensor: "Q"
    mode: 3
    format: "compressed"
    src: true
    label: "FiberLookup m: Q3\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 15
  joiner {
    input_pairs {
      crd {
        id {
          id: 1023
        }
        name: "crd_in-Q"
      }
      ref {
        id {
          id: 1031
        }
        name: "ref_in-Q"
      }
    }
    input_pairs {
      crd {
        id {
          id: 1033
        }
        name: "crd_in-K"
      }
      ref {
        id {
          id: 1034
        }
        name: "ref_in-K"
      }
    }
    index: "m"
    label: "intersect m"
    output_ref1 {
      id {
      }
      name: "out-Q"
    }
    output_ref2 {
      id {
      }
      name: "out-K"
    }
    output_crd {
      id {
        id: 1019
      }
      name: "in-m"
    }
  }
}
operators {
  name: "arrayvals"
  id: 9
  array {
    tensor: "Q"
    input_ref {
      id {
        id: 1025
      }
      name: "ref_out-Q"
    }
    output_val {
      id {
      }
      name: "val"
    }
    label: "Array Vals: Q"
  }
}
operators {
  name: "mul"
  id: 8
  alu {
    vals {
      inputs {
        id {
          id: 1026
        }
        name: "val"
      }
      inputs {
        id {
          id: 1030
        }
        name: "val"
      }
      output {
        id {
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "reduce"
  id: 7
  reduce {
    input_val {
      id {
        id: 1027
      }
      name: "val"
    }
    output_val {
      id {
      }
      name: "val"
    }
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 1028
      }
      name: "val"
    }
    label: "FiberWrite Vals: X"
    crdsize: "1*Q0_dim*Q2_dim*Q1_dim*K1_dim"
    tensor: "X"
    sink: true
  }
}
operators {
  name: "arrayvals"
  id: 10
  array {
    tensor: "K"
    input_ref {
      id {
        id: 1029
      }
      name: "ref_out-K"
    }
    output_val {
      id {
        id: 1027
      }
      name: "val"
    }
    label: "Array Vals: K"
  }
}
operators {
  name: "fiberlookup"
  id: 17
  fiber_lookup {
    input_ref {
      id {
        id: 1032
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 1029
      }
      name: "in-K"
    }
    output_crd {
      id {
        id: 1029
      }
      name: "in-K"
    }
    index: "m"
    tensor: "K"
    mode: 3
    format: "compressed"
    src: true
    label: "FiberLookup m: K3\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 28
  fiber_lookup {
    input_ref {
      id {
        id: 1038
      }
      name: "ref_out-K"
    }
    output_ref {
      id {
        id: 1036
      }
      name: "in-K"
    }
    output_crd {
      id {
        id: 1036
      }
      name: "in-K"
    }
    index: "j"
    tensor: "K"
    mode: 2
    format: "compressed"
    src: true
    label: "FiberLookup j: K2\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 31
  fiber_lookup {
    output_ref {
      id {
        id: 1038
      }
      name: "in-K"
    }
    output_crd {
      id {
        id: 1038
      }
      name: "in-K"
    }
    index: "i"
    tensor: "K"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup i: K0\\ncompressed"
  }
}

