# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tortilla.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ops_pb2 as ops__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etortilla.proto\x12\x08tortilla\x1a\tops.proto\"J\n\x0cProgramGraph\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\toperators\x18\x02 \x03(\x0b\x32\x13.tortilla.OperationJ\x04\x08\x03\x10\x0b\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tortilla_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROGRAMGRAPH']._serialized_start=39
  _globals['_PROGRAMGRAPH']._serialized_end=113
# @@protoc_insertion_point(module_scope)
