# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tortilla.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ops_pb2 as ops__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tortilla.proto',
  package='tortilla',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etortilla.proto\x12\x08tortilla\x1a\tops.proto\"J\n\x0cProgramGraph\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\toperators\x18\x02 \x03(\x0b\x32\x13.tortilla.OperationJ\x04\x08\x03\x10\x0b\x62\x06proto3'
  ,
  dependencies=[ops__pb2.DESCRIPTOR,])




_PROGRAMGRAPH = _descriptor.Descriptor(
  name='ProgramGraph',
  full_name='tortilla.ProgramGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tortilla.ProgramGraph.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operators', full_name='tortilla.ProgramGraph.operators', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=113,
)

_PROGRAMGRAPH.fields_by_name['operators'].message_type = ops__pb2._OPERATION
DESCRIPTOR.message_types_by_name['ProgramGraph'] = _PROGRAMGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProgramGraph = _reflection.GeneratedProtocolMessageType('ProgramGraph', (_message.Message,), {
  'DESCRIPTOR' : _PROGRAMGRAPH,
  '__module__' : 'tortilla_pb2'
  # @@protoc_insertion_point(class_scope:tortilla.ProgramGraph)
  })
_sym_db.RegisterMessage(ProgramGraph)


# @@protoc_insertion_point(module_scope)
